name: Generic

on:
  repository_dispatch:
    types:
      - run-jobs

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Puting error to check
        run: |
          sudo mkdie /home/error_log

      - name: Example Step
        run: |
          echo "Environment: ${{ github.event.client_payload.environment }}"
          echo "Version: ${{ github.event.client_payload.version }}"