name: Generic

on:
  repository_dispatch:
    types:
      - run-jobs

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Example Step
        run: echo "This job was triggered by Repo B!"